### DISCUSSION TITLE
Resources/namespace assign from one to another tennant

### DISCUSSION THREAD

**Discussion by msergg** [projectcapsule/capsule#774] [Q&A]
Where can I find description or some docs
how to assign to existing namespaces without tenant or migrate to another tenant?

Adding label `capsule.clastix.io/tenant: <tennant>` is not working
Cant figure out what I messed

Thanks for support

**Comment by msergg** [comment]
look like need to add block, is it?

```
 ownerReferences:
    - apiVersion: capsule.clastix.io/v1beta2
      kind: Tenant
      name: test-team
      uid: 1b17fb95-b49b-4b77-925a-771b6fff41ab
      controller: true
      blockOwnerDeletion: true
```
