### ISSUE TITLE
Capsule upgrade from 0.7.2 -> 0.7.3 failing in FluxCD due to missing capsule-capsule-proxy-certgen Job

### ISSUE THREAD

**Issue by heytrav** [projectcapsule/capsule#1360]
# Bug description

FluxCD is failing to upgrade Capsule from v0.7.2 -> v0.7.3 and reporting the following:
```
Helm upgrade failed for release capsule/capsule-capsule with chart capsule@0.7.3: jobs.batch "capsule-capsule-proxy-certgen" not found
```

The Job doesn't exist, but I'm not sure why it is not being created. Running
```
helm template capsule projectcapsule/capsule --set serviceMonitor.enabled=true --set proxy.enabled=true --set certManager.generateCertificates=true --set fullnameOverride=capsule-capsule
```
Produces yaml with a `capsule-proxy-certgen` job, but i haven't figured out why Fluxcd isn't creating it.
# How to reproduce

1. Provide the Capsule Tenant YAML definitions
2. Provide all managed Kubernetes resources

```
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capsule
  namespace: flux-system
spec:
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: capsule
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: projectcapsule
      version: '>=0.7.2 < 0.8.0'
  install:
    crds: Create
    createNamespace: true
    remediation:
      retries: -1
  interval: 5m0s
  targetNamespace: capsule
  upgrade:
    crds: CreateReplace
  values:
    serviceMonitor:
      enabled: true
    proxy:
      enabled: true
    certManager:
      generateCertificates: true
    # tls:
    #   enableController: false
    fullnameOverride: capsule-capsule

```

# Expected behavior

I expect the Job to be created when FluxCD automatically upgraded the helm chart.

# Logs

If applicable, please provide logs of `capsule`.

In a standard stand-alone installation of Capsule,
you'd get this by running `kubectl -n capsule-system logs deploy/capsule-controller-manager`.

# Additional context

- Capsule version: (`capsule --version`)
- Helm Chart version: (`helm list -n capsule-system`)
- Kubernetes version: (`kubectl version`)
