### ISSUE TITLE
How to use the capsule project with the argocd gitops approach

### ISSUE THREAD

**Issue by djkormo** [projectcapsule/capsule#1397]
# How to use the capsule project with the argocd gitops approach

Capsule was installed using helm chart with version 0.7.4

How to sync namespaces resources

1. Provide the Capsule Tenant YAML definitions

My capsule configuration

```yaml
apiVersion: capsule.clastix.io/v1beta2
kind: CapsuleConfiguration
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: capsule
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: capsule
    app.kubernetes.io/version: 0.7.4
    argocd.argoproj.io/instance: capsule
    helm.sh/chart: capsule-0.7.4
  name: default
spec:
  enableTLSReconciler: false
  forceTenantPrefix: false
  nodeMetadata:
    forbiddenAnnotations:
      denied: []
      deniedRegex: ''
    forbiddenLabels:
      denied: []
      deniedRegex: ''
  overrides:
    TLSSecretName: capsule-tls
    mutatingWebhookConfigurationName: capsule-mutating-webhook-configuration
    validatingWebhookConfigurationName: capsule-validating-webhook-configuration
  protectedNamespaceRegex: "^(kube-system|kube-public|kube-node-lease|kube-kube-.*|default|capsule-systems)$"
  userGroups:
    - projectcapsule.dev
    - system:serviceaccounts:argocd
    - system:admin
    - system:masters
```

My tenant configuration

```yaml
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  labels:
    argocd.argoproj.io/instance: capsule-systems
  name: destroyer
spec:
  cordoned: false
  forceTenantPrefix: false
  limitRanges:
    items:
      - limits:
          - default:
              cpu: 500m
              memory: 512Mi
            defaultRequest:
              cpu: 100m
              memory: 10Mi
            type: Container
  namespaceOptions:
    additionalMetadata:
      labels:
        application: destroyer
    quota: 3 # number of namespaces per tenant
  owners:
    - kind: User
      name: system:admin
    - kind: User
      name: my-user
    - kind: ServiceAccount
      name: system:serviceaccounts:argocd
  resourceQuotas:
    items:
      - hard:
          limits.cpu: '7'
          limits.memory: 16Gi
          requests.cpu: '7'
          requests.memory: 16Gi
      - hard:
          pods: '100'
    scope: Namespace
```

2. Provide all managed Kubernetes resources

My namespaces configuration

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: destroyer-dev
  labels:
    capsule.clastix.io/tenant: destroyer
    purpose: development   
--- 
apiVersion: v1
kind: Namespace
metadata:
  name: destroyer-uat
  labels:
    capsule.clastix.io/tenant: destroyer
    purpose: testing   
--- 
apiVersion: v1
kind: Namespace
metadata:
  name: destroyer-prd
  labels:
    capsule.clastix.io/tenant: destroyer
    purpose: production   
```

My argocd application

```yaml

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capsule-systems
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'http://gogs-svc.default.svc.cluster.local:18080/gogs/argocd-apps.git' # my local git installed on kubernetes
    targetRevision: HEAD
    path: capsule-systems

  destination:
    server: https://kubernetes.default.svc
    namespace:  capsule-systems

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true

```

# How to reproduce

Argocd is used to synchronize tenant manifest and namespaces manifests

![Image](https://github.com/user-attachments/assets/58f01aa2-0e2e-4fa3-8e44-15d0436bc4c9)

# Expected behavior

After syncing resources (here namespace) in argocd they should be added to  tenant with owner reference.

When I try to sync them (the namespace is not created yet) I see  

![Image](https://github.com/user-attachments/assets/10acabf6-3481-47b8-9544-2d1c766f8ff5)
<pre>
admission webhook "owner.namespace.projectcapsule.dev" denied the request: Cannot assign the desired namespace to a non-owned Tenant
</pre>

In the capsule controller logs I see

<pre>
{"level":"Level(-5)","ts":"2025-03-09T14:20:32.095Z","logger":"admission","msg":"received request","object":{"name":"destroyer-uat","namespace":"destroyer-uat"},"namespace":"destroyer-uat","name":"destroyer-uat","resource":{"group":"","version":"v1","resource":"namespaces"},"user":"system:serviceaccount:argocd:argocd-application-controller","requestID":"eb29c740-7c3c-4e14-8787-aabe236a0398"}
{"level":"Level(-5)","ts":"2025-03-09T14:20:32.095Z","logger":"admission","msg":"wrote response","code":403,"reason":"Forbidden","message":"Cannot assign the desired namespace to a non-owned Tenant","requestID":"eb29c740-7c3c-4e14-8787-aabe236a0398","allowed":false}
{"level":"debug","ts":"2025-03-09T14:20:32.095Z","logger":"events","msg":"Namespace destroyer-uat cannot be assigned to the current Tenant","type":"Warning","object":{"kind":"Tenant","name":"destroyer","uid":"05a8ac6b-7556-4f55-b247-bbe3e89bf0bd","apiVersion":"capsule.clastix.io/v1beta2","resourceVersion":"21037528"},"reason":"NonOwnedTenant"}
</pre>

When the namespace is created outside argocd and having  owner reference added to a namespace I see

![Image](https://github.com/user-attachments/assets/586b5494-c443-4679-8bac-0d8930b922b2)

<pre>
error when patching "/dev/shm/2783867173": admission webhook "owner.namespace.projectcapsule.dev" denied the request: Denied patch request for this namespace
</pre>

In logs I see

<pre>
{"level":"Level(-5)","ts":"2025-03-09T14:23:49.175Z","logger":"admission","msg":"received request","object":{"name":"destroyer-dev","namespace":"destroyer-dev"},"namespace":"destroyer-dev","name":"destroyer-dev","resource":{"group":"","version":"v1","resource":"namespaces"},"user":"system:serviceaccount:argocd:argocd-application-controller","requestID":"5261797d-9d90-4b9a-a946-3e6a61817a5c"}
{"level":"Level(-5)","ts":"2025-03-09T14:23:49.175Z","logger":"admission","msg":"wrote response","code":403,"reason":"Forbidden","message":"Denied patch request for this namespace","requestID":"5261797d-9d90-4b9a-a946-3e6a61817a5c","allowed":false}
{"level":"debug","ts":"2025-03-09T14:23:49.175Z","logger":"events","msg":"Namespace destroyer-dev can not be patched","type":"Warning","object":{"kind":"Namespace","name":"destroyer-dev","uid":"a30b4a8c-936f-472b-b999-9ea97508bbc5","apiVersion":"v1","resourceVersion":"21037533"},"reason":"OfflimitNamespace"}
</pre>

# Additional context

- Capsule version: ghcr.io/projectcapsule/capsule:v0.7.4
- Helm Chart version: 0.7.4
- Kubernetes version: 1.29.12
