### ISSUE TITLE
Proxy settings in Tenants v1alpha1 are not migrated to v1beta1

### ISSUE THREAD

**Issue by bsctl** [projectcapsule/capsule#409]
# Bug description
Proxy settings in Tenants `v1alpha1` are not migrated to `v1beta1`

# How to reproduce

```yaml
kubectl apply -f - << EOF
apiVersion: capsule.clastix.io/v1alpha1
kind: Tenant
metadata:
  name: alpha
  annotations:
    capsule.clastix.io/enable-node-listing: "true"
spec:
  owner: # required
    name: ecumenos
    kind: Group
EOF
```

is translated as 

```yaml
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: alpha
spec:
  owners:
  - kind: Group
    name: ecumenos
```

# Expected behavior

```yaml
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: alpha
spec:
  owners:
  - kind: Group
    name: ecumenos
    proxySettings:
    - kind: Nodes
      operations:
      - List
```

# Logs

If applicable, please provide logs of `capsule`.

In a standard stand-alone installation of Capsule,
you'd get this by running `kubectl -n capsule-system logs deploy/capsule-controller-manager`.

# Additional context

- Capsule version: v0.1.0
- Helm Chart version: (`helm list -n capsule-system`)
- Kubernetes version: (`kubectl version`)
