### ISSUE TITLE
Automation providing capsule-proxy kubeConfig to in-cluster GitOps automation

### ISSUE THREAD

**Issue by erikgb** [projectcapsule/capsule#770]
# Describe the feature

We would like to use FluxCD (or other in-cluster GitOps tool) with Capsule to allow regular users to provision namespaces. First, we tried without the capsule-proxy, but it seems like the proxy is required for the Flux reconciling approach to work, and that's fair. Making the Flux tenant gitops-reconciler service account go through the proxy is possible, but currently requires manual cluster-admin work (ref. `proxy-kubeconfig-generator` in https://capsule.clastix.io/docs/guides/flux2-capsule/#the-recipe). This does not scale IMO, and I would like an automated solution to provide capsule-proxy `kubeConfig`.

Related issue: https://github.com/clastix/capsule/issues/608

# What would the new user story look like?

As a cluster-admin I want automation to provide a capsule-proxy `kubeConfig` secret for in-cluster access to kube-apiserver through the proxy. This will allow me to avoid manual tasks for onboarding new tenants.

# Expected behavior

Ref. https://capsule.clastix.io/docs/guides/flux2-capsule/#the-recipe, I think it the UI could as simple as annotating the tenant gitops-reconciler service account with an indication of the name of the secret the `kubeConfig` should be delivered to. Example:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-reconciler
  namespace: my-tenant
  annotations:
    capsule.clastix.io/kubeconfig-secret-name: gitops-reconciler-kubeconfig
```

This should make the automation (capsule-controller) deliver and maintain the `kubeConfig` secret:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: gitops-reconciler-kubeconfig
  namespace: my-tenant
data:
  kubeconfig: ......
```

**Comment by prometherion** [comment]
I like the idea of automating the deployment of the `kubeconfig`.

Since we're talking about the `capsule-proxy`, BTW, I think this should be delegated to that project, since without it the FluxCD integration cannot work as expected.

@MaxFedotov @maxgio92 @bsctl @oliverbaehler WDYT?

**Comment by erikgb** [comment]
> Since we're talking about the capsule-proxy, BTW, I think this should be delegated to that project, since without it the FluxCD integration cannot work as expected.

That makes sense. I wasn't fully aware of capsule-proxy being a separate proxy. Sorry.

**Comment by erikgb** [comment]
After thinking a bit more about this, I think it makes more sense to focus on the secret and rely on a K8s feature, as this will probably make the machinery simpler and less error-prone. So my modified suggestion is the following.

The user creates the secret where he/she wants to obtain the capsule-proxy kubeconfig:

````yaml
apiVersion: v1
kind: Secret
metadata:
  name: gitops-reconciler-kubeconfig
  namespace: my-tenant
  annotations:
    kubernetes.io/service-account.name: gitops-reconciler
    capsule.clastix.io/kubeconfig: generate
type: kubernetes.io/service-account-token
````

When the Kubernetes controller has done its job adding the token++ to the secret, the Capsule controller can use the token to generate the `kubeConfig` and add it to the secret. The resulting secret might look like this:

````yaml
kind: Secret
apiVersion: v1
metadata:
  name: gitops-reconciler-kubeconfig
  namespace: my-tenant
  annotations:
    capsule.clastix.io/kubeconfig: generate
    kubernetes.io/service-account.name: gitops-reconciler
    kubernetes.io/service-account.uid: 7dfa681c-f6a9-4b15-969a-e5e7ac834ace
data:
  ca.crt: ....
  kubeconfig: ...
  service-ca.crt: ...
  token: ...
type: kubernetes.io/service-account-token
````
