### ISSUE TITLE
Tenant annotations for CRD instances quota is not reflecting the proper value

### ISSUE THREAD

**Issue by prometherion** [projectcapsule/capsule#899]
# Bug description

Create a Tenant with the annotation `quota.resources.capsule.clastix.io` to limit the amount of Custom Resource instances.

```yaml
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  annotations:
    quota.resources.capsule.clastix.io/tenantcontrolplanes.kamaji.clastix.io_v1alpha1: "3"
  name: solar
spec:
...
```

By deleting one by one, the used annotation (`used.resources.capsule.clastix.io/tenantcontrolplanes.kamaji.clastix.io_v1alpha1`) doesn't reflect the proper value.

# How to reproduce

1. Create a Tenant with limited CR instances
2. Create 2 or more
3. delete one by one
4. check the used annotation which is still pointing to a non correct value

# Expected behavior

The annotation should report the correct value.

# Logs

N.R.

# Additional context

- Capsule version: `v0.4.1`
- Helm Chart version: N.R.
- Kubernetes version: N.R.
