### ISSUE TITLE
Reconcile tenant resources with annotations fail

### ISSUE THREAD

**Issue by ppodevlabs** [projectcapsule/capsule#916]
# Bug description
Tenant resource with annotations inside fails to be reconciled as the capsule controller does not parse properly the raw items

# How to reproduce

```
apiVersion: capsule.clastix.io/v1beta2
kind: TenantResource
metadata:
  name: gitops-reconciler
  namespace: test-home
spec:
  resyncPeriod: 5m
  resources:
    - namespaceSelector:
        matchLabels:
          capsule.clastix.io/tenant: test
      rawItems:
      - apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: gitops-reconciler
      - apiVersion: v1
        kind: Secret
        type: kubernetes.io/service-account-token
        metadata:
          annotations:
            kubernetes.io/service-account.name: gitops-reconciler
          name: gitops-reconciler
          namespace: test-home
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          name: gitops-reconciler
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: cluster-admin
        subjects:
        - kind: ServiceAccount
          name: gitops-reconciler
```
Produce an error stating that the annotation under the secret does not have a value.

# Expected behavior

the resources defined under rawItems should be reconciled into the cluster.

# Logs
```
{"level":"error","ts":"2023-11-30T16:26:34.314Z","msg":"Reconciler error","controller":"tenantresource","controllerGroup":"capsule.clastix.io","controllerKind":"TenantResource","TenantResource":{"name":"gitops-reconciler","namespace":"test-home"},"namespace":"test-home","name":"gitops-reconciler","reconcileID":"89aaf19a-3cc0-4c76-ac36-aa48cf1d7835","error":"1 error occurred:\n\t* Secret \"gitops-reconciler\" is invalid: metadata.annotations[kubernetes.io/service-account.name]: Required value\n\n","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"}
```

# Additional context

- Capsule version: 0.4.2
- Helm Chart version: 0.5.3
- Kubernetes version: 1.26.3
