### ISSUE TITLE
object count resource quotas not working and breaking other Tenant functionality

### ISSUE THREAD

**Issue by adabuleanu** [projectcapsule/capsule#942]
# Bug description

The `Tenant` CR let's you define the [kubernetes resource quotas](https://capsule.clastix.io/docs/general/crds-apis/#tenantspecresourcequotas-1). One such resource quota is [object count](https://kubernetes.io/docs/concepts/policy/resource-quotas/#object-count-quota), for example jobs count is defined by `count/jobs.batch`. While defining such configuration, the `Tenant` object is created, but this silently fails. Moreover, so of the other functionality is not working as expected. This was initially fixed in https://github.com/projectcapsule/capsule/issues/507 in v1beta1 api, but somehow it was not moved to [v1beta2](https://github.com/projectcapsule/capsule/issues/507)

# How to reproduce

1. Create a `Tenant` resource:
```
apiVersion: capsule.clastix.io/v1beta2
kind: Tenant
metadata:
  name: dummytenant
  owners:
  - clusterRoles:
    - admin
    - capsule-namespace-deleter
    kind: ServiceAccount
    name: system:serviceaccount:ns:dummy
  resourceQuotas:
    items:
    - hard:
        count/jobs.batch: "2"
        limits.cpu: 300m
        limits.ephemeral-storage: 1Gi
        limits.memory: 1200Mi
    scope: Tenant
```
2. Check the underlying `ResourceQuota` created, it should not contain any jobs quota.
3. Moreover, try to create a `Namespace` as the owner:
```
kubectl --as=system:serviceaccount:ns:dummy create ns dummytenant-ns1
```
4. This will create the namespace successfully, but when you try to access it with the same owner `ServiceAccount`, you will not be allowed:
```
$ kubectl -as=system:serviceaccount:ns:dummy get ns dummytenant-ns1
Error from server (Forbidden): namespaces "dummytenant-ns1" is forbidden: User "system:serviceaccount:ns:dummy " cannot get resource "namespaces" in API group "" in the namespace "dummytenant-ns1"
```
This is caused by the fact that capsule does not created the `RoleBindings` associated with the new namespace. If you check the  `RoleBindings` you will not see any created for the respective `Namespace`
```
$ kubectl get rolebindings -A | grep dummytenant
```
5. If you repeat all steps above without the `count/jobs.batch` configuration, the `RoleBindings` will be created as expected.

# Expected behavior

- `Tenant` should be able to define `count/jobs.batch` `ResourceQuotas`.
- Errors related to a configuration should not perpetuate to other functionality (see `Namespace` example above).

# Logs

Error logs
```
ResourceQuota \"capsule-dummytenant-0\" is invalid: [metadata.annotations: Invalid value: \"quota.capsule.clastix.io/hard-count/jobs.batch\": a qualified name must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an optional DNS subdomain prefix and '/' (e.g. 'example.com/MyName'), metadata.annotations: Invalid value: \"quota.capsule.clastix.io/used-count/jobs.batch\": a qualified name must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an optional DNS subdomain prefix and '/' (e.g. 'example.com/MyName')]
```

# Additional context

- Capsule version: v0.3.3
- Helm Chart version:  0.4.3
- Kubernetes version: v1.27.7
